/**
 * 批量导入黑客松到草稿箱
 * 运行: npx tsx scripts/batch-import-hackathons.ts
 */
import { config } from 'dotenv';
config({ path: '.env.local' });

import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { draftHackathons } from '../lib/db/schema';

const connectionString = process.env.DATABASE_URL!;
const client = neon(connectionString);
const db = drizzle(client);

interface HackathonDraft {
  sourceUrl: string;
  platform: string;
  name: string;
  shortName?: string;
  city: string;
  country: string;
  venue?: string;
  dateRange: string;
  startDate?: string;
  endDate?: string;
  format: string;
  theme?: string;
  summary: string;
  prizePool?: string;
  teams?: string;
  tracks?: string[];
  organizers?: string[];
  sponsors?: string[];
  confidence: number;
}

const hackathonData: HackathonDraft[] = [
  // ============ 北京 (9) ============
  {
    sourceUrl: "https://www.ethbeijing.xyz/",
    platform: "web",
    name: "ETH Beijing 2026 | AI x Web3 Hackathon",
    shortName: "ETH Beijing 2026",
    city: "北京",
    country: "中国",
    venue: "昆仑巢，融科信息中心 A 座 9 层，海淀区",
    dateRange: "2026年6月5日-7日",
    startDate: "2026-06-05",
    endDate: "2026-06-07",
    format: "offline",
    theme: "拥抱 Web3 AI 时代 — AI Agent x Blockchain",
    summary: "由 PKU Blockchain DAO 和 WTF Academy 联合举办的 Web3 + AI 线下黑客松，72 小时现场开发。项目必须在赛期内从零开始，第三天 Demo 展示和颁奖。",
    prizePool: "¥21,000",
    tracks: ["AI Agent x Blockchain", "Public Good", "Security/Risk Agent", "AI for Transparency"],
    organizers: ["PKU Blockchain DAO", "WTF Academy"],
    confidence: 90,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "Mother Board「生·无界」母亲节特别场黑客松 | 北京站",
    shortName: "Mother Board 北京站",
    city: "北京",
    country: "中国",
    venue: "海淀区东升大厦 A 座 9 层原点学堂",
    dateRange: "2026年5月9日-10日",
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    format: "offline",
    theme: "女性生命体验与技术创造 — 生命、生长、生产",
    summary: "以母亲节为契机的女性主题黑客松，聚焦生命、生长、生产三个维度，鼓励女性参与技术创作。",
    organizers: ["观猹 Insights", "She Nicest"],
    confidence: 75,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "40 小时 StartBuild 黑客松 北京站",
    shortName: "StartBuild 北京站",
    city: "北京",
    country: "中国",
    venue: "北京理工大学科技园",
    dateRange: "2026年4月24日-26日",
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    format: "offline",
    theme: "大学生创新创业",
    summary: "面向全日制在校大学生的 40 小时线下黑客松，提供食宿补给与导师陪跑，免费参加。",
    confidence: 70,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "超越之路 Ultra Maker 黑客松 2026 | 北京站",
    shortName: "Ultra Maker 北京站",
    city: "北京",
    country: "中国",
    venue: "海淀 ePark（花园路社区，花园北路 25 号）",
    dateRange: "2026年4月3日-6日",
    startDate: "2026-04-03",
    endDate: "2026-04-06",
    format: "offline",
    theme: "AI 时代超级个体与超级团队",
    summary: "以 '48 小时用创造回应世界' 为口号的多日线下黑客松，聚焦 AI 时代超级个体与超级团队的可能性。",
    confidence: 70,
  },
  {
    sourceUrl: "https://dorahacks.io/hackathon/flagos-open-computing/detail",
    platform: "dorahacks",
    name: "FlagOS Open Computing Global Challenge",
    shortName: "FlagOS 黑客松",
    city: "北京",
    country: "中国",
    dateRange: "2026年1月-6月（Season 1）",
    startDate: "2026-01-09",
    endDate: "2026-06-10",
    format: "hybrid",
    theme: "AI 系统软件栈开源开发与创新",
    summary: "由 FlagOS 社区、北京智源人工智能研究院（BAAI）和 CCF 联合举办的多赛季竞赛，基于 FlagOS 统一 AI 系统软件栈进行实践创作。",
    prizePool: "¥2,000,000",
    organizers: ["FlagOS Community", "北京智源人工智能研究院（BAAI）", "CCF 开源发展技术委员会"],
    confidence: 85,
  },
  {
    sourceUrl: "https://english.beijing.gov.cn/beijinginfo/sci/latesttrends/202603/t20260327_4567695.html",
    platform: "web",
    name: "ZGC Forum 2026 AI Workshop 黑客松（创世之夜）",
    shortName: "ZGC AI Workshop",
    city: "北京",
    country: "中国",
    venue: "东升大厦 A 座，AI 创世社区",
    dateRange: "2026年3月25日-29日",
    startDate: "2026-03-25",
    endDate: "2026-03-29",
    format: "offline",
    theme: "全球化出海、Vibe Coding、AIGC 创作、OpenClaw",
    summary: "中关村论坛 2026 年会的创世之夜活动，300 名年轻开发者参与 AI Workshop 黑客松。",
    teams: "300",
    tracks: ["全球化出海", "Vibe Coding", "AIGC 创作", "OpenClaw"],
    organizers: ["中关村论坛（ZGC Forum）"],
    confidence: 80,
  },
  {
    sourceUrl: "https://www.v2ex.com/t/1206299",
    platform: "v2ex",
    name: "打造你的首个 AI 员工 Workshop",
    shortName: "AI 员工 Workshop",
    city: "北京",
    country: "中国",
    dateRange: "2026年4月3日",
    startDate: "2026-04-03",
    endDate: "2026-04-03",
    format: "offline",
    theme: "OpenClaw 实战 — 打造首个 AI 员工",
    summary: "由 AI Burrow 和 first AIde 联合举办的 OpenClaw 实战工作坊/黑客松。",
    organizers: ["AI Burrow", "first AIde"],
    confidence: 65,
  },
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/urlsc4fcfd35911c24bfcf013004506f74b3",
    platform: "competehub",
    name: "智能渗透挑战赛",
    shortName: "智能渗透挑战赛",
    city: "北京",
    country: "中国",
    dateRange: "2026年4月10日-20日",
    startDate: "2026-04-10",
    endDate: "2026-04-20",
    format: "offline",
    theme: "网络安全 / 渗透测试",
    summary: "网络安全主题黑客松，聚焦渗透测试与安全攻防。",
    prizePool: "¥100,000",
    tracks: ["Cybersecurity", "Penetration Testing"],
    confidence: 70,
  },
  {
    sourceUrl: "https://en.zhenfund.com/Hackathon",
    platform: "web",
    name: "ZhenFund x AWS x Linkloud Growth Hackathon",
    shortName: "真格 Growth Hackathon",
    city: "北京",
    country: "中国",
    dateRange: "2026年6月10日-11日",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    format: "offline",
    theme: "生成式 AI 出海创业",
    summary: "中国首个专为出海生成式 AI 创业公司设计的 Growth Hackathon，含一天会议和 24 小时黑客松。优胜团队可获真格基金天使投资。",
    organizers: ["真格基金", "Amazon Web Services", "Linkloud"],
    sponsors: ["Amazon Web Services"],
    confidence: 85,
  },

  // ============ 上海 (10) ============
  {
    sourceUrl: "https://news.qq.com/rain/a/20260421A05TWW00",
    platform: "web",
    name: "上海·徐汇量子黑客松大赛 2026",
    shortName: "徐汇量子黑客松",
    city: "上海",
    country: "中国",
    venue: "徐汇源点大厦（徐汇西岸）",
    dateRange: "2026年5月16日-17日",
    startDate: "2026-05-16",
    endDate: "2026-05-17",
    format: "offline",
    theme: "量子计算前沿技术与产业应用",
    summary: "48 小时极限挑战，30 支队伍、5 大赛道同台竞技，涵盖量子算法优化、气象海洋、科学计算、能源工业、智能视觉。",
    prizePool: "¥500,000",
    teams: "30",
    tracks: ["量子算法优化", "气象海洋", "科学计算", "能源工业", "智能视觉"],
    organizers: ["徐汇区科学技术委员会", "上海未来产业基金"],
    sponsors: ["上海汇智投资有限公司", "开源中国"],
    confidence: 90,
  },
  {
    sourceUrl: "https://finance.sina.com.cn/tech/digi/2026-03-20/doc-inhrrrew0783510.shtml",
    platform: "xiaohongshu",
    name: "小红书首届黑客松巅峰赛",
    shortName: "小红书黑客松",
    city: "上海",
    country: "中国",
    venue: "张江人工智能创新小镇（张江科学会堂）",
    dateRange: "2026年4月7日-10日",
    startDate: "2026-04-07",
    endDate: "2026-04-10",
    format: "offline",
    theme: "AI 原生创造，软件+硬件双赛道",
    summary: "小红书首届黑客松巅峰赛，200 名选手 48 小时封闭开发，从零打造 AI 软件或硬件产品。60%+ 参赛者为 00 后，最小选手仅 12 岁。",
    prizePool: "¥500,000",
    tracks: ["软件赛道", "硬件赛道"],
    organizers: ["小红书"],
    confidence: 95,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "LYCC 2026 龙华黑客松",
    shortName: "龙华黑客松",
    city: "上海",
    country: "中国",
    venue: "西岸大剧院（龙腾大道 2290 号，徐汇区）",
    dateRange: "2026年4月25日-26日",
    startDate: "2026-04-25",
    endDate: "2026-04-26",
    format: "offline",
    theme: "AI 赋能青年消费、交通、居住三大场景",
    summary: "「龙华创意青年π」活动的核心黑客松，面向青年开发者，聚焦消费、交通、居住三大赛道。",
    prizePool: "¥14,000",
    tracks: ["青年消费", "交通", "居住"],
    organizers: ["向心龙华", "久事交通"],
    confidence: 75,
  },
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/luma9d25ea8393c28a28732c4e1c4347b15f",
    platform: "competehub",
    name: "2026 空间上海：24 小时 AR/VR 黑客马拉松",
    shortName: "空间上海 AR/VR",
    city: "上海",
    country: "中国",
    dateRange: "2026年4月25日-26日",
    startDate: "2026-04-25",
    endDate: "2026-04-26",
    format: "offline",
    theme: "AR/VR/XR 沉浸式开发",
    summary: "24 小时 AR/VR 黑客马拉松，聚焦空间计算和沉浸式技术应用开发。",
    tracks: ["AR/VR", "Spatial Computing"],
    confidence: 65,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "上海 AI 超级产品黑客松",
    shortName: "AI 超级产品黑客松",
    city: "上海",
    country: "中国",
    dateRange: "2026年5月8日",
    startDate: "2026-05-08",
    endDate: "2026-05-08",
    format: "offline",
    theme: "Vibe Coding 构建 AI 产品",
    summary: "半天教学+半天比赛的 AI 产品黑客松，使用 Vibe Coding 方式快速构建 AI 产品。",
    organizers: ["随缘码头"],
    confidence: 65,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "Mother Board「生·无界」母亲节特别场黑客松 | 上海站",
    shortName: "Mother Board 上海站",
    city: "上海",
    country: "中国",
    venue: "香港科技大学上海中心",
    dateRange: "2026年5月9日-10日",
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    format: "offline",
    theme: "女性生命经验与技术创造",
    summary: "聚焦女性生命经验与技术创造的母亲节特别场黑客松，以生命、成长与创造为主题。",
    organizers: ["观猹 Insights", "She Nicest"],
    confidence: 75,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "Ship it Sunday #009 | Make something agents want",
    shortName: "Ship it Sunday",
    city: "上海",
    country: "中国",
    venue: "AI Hacker House Shanghai, 漕河泾开发区",
    dateRange: "2026年5月17日",
    startDate: "2026-05-17",
    endDate: "2026-05-17",
    format: "offline",
    theme: "为 AI Agent 构建可用工具与环境",
    summary: "月度 AI 黑客松，聚焦为 AI Agent 构建可用的工具与环境。",
    organizers: ["十字路口 Crossing", "AI Hacker House"],
    confidence: 70,
  },
  {
    sourceUrl: "https://www.mwcshanghai.com/articles/gsma-china-telecom-open-gateway-hackathon",
    platform: "web",
    name: "GSMA-中国电信 Open Gateway 编程马拉松",
    shortName: "GSMA Open Gateway 黑客松",
    city: "上海",
    country: "中国",
    venue: "上海新国际博览中心（MWC Shanghai 2026）",
    dateRange: "2026年6月24日-26日",
    startDate: "2026-06-24",
    endDate: "2026-06-26",
    format: "offline",
    theme: "电信 Open Gateway API 创新应用",
    summary: "GSMA 与中国电信联合举办，在 MWC Shanghai 2026 期间举行。参赛作品须使用至少一个 Open Gateway 标准能力 API。",
    organizers: ["GSMA", "中国电信"],
    confidence: 85,
  },
  {
    sourceUrl: "https://www.cnblogs.com/OpenCSG/p/19696217",
    platform: "web",
    name: "OPC 独立先锋挑战赛（WAIC 2026）",
    shortName: "OPC 先锋挑战赛",
    city: "上海",
    country: "中国",
    venue: "上海世博中心（WAIC 2026）",
    dateRange: "2026年4月-7月",
    startDate: "2026-04-01",
    endDate: "2026-07-31",
    format: "hybrid",
    theme: "AI 赋能「超级个体」创业",
    summary: "WAIC 2026 首个重磅赛事，聚焦 AI 时代「超级个体」创业，覆盖 10 个核心城市。",
    tracks: ["OPC·创业赛道", "OPC·创新赛道"],
    organizers: ["世界人工智能大会 (WAIC)"],
    confidence: 80,
  },
  {
    sourceUrl: "https://www.aitop100.cn/infomation/details/27186.html",
    platform: "web",
    name: "首届「燕缘·滴水湖」大学生 AI+ 国际创业大赛",
    shortName: "燕缘·滴水湖 AI 创业赛",
    city: "上海",
    country: "中国",
    venue: "上海临港滴水湖畔",
    dateRange: "2026年6月-10月",
    startDate: "2026-06-16",
    endDate: "2026-10-19",
    format: "hybrid",
    theme: "AI+ 多场景创业",
    summary: "面向大学生的 AI+ 国际创业大赛，总价值超 200 万元奖励，7 大赛道涵盖智慧文旅、AI 教育等。",
    prizePool: "¥2,000,000+",
    tracks: ["智慧文旅", "智慧家居", "AI 社交", "AI 教育", "智慧城市", "智慧商贸"],
    organizers: ["青年报社", "南汇新城镇人民政府", "上海临港北大人工智能创新中心"],
    sponsors: ["华为昇腾 AI", "阿里云"],
    confidence: 80,
  },

  // ============ 广州 (3) ============
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/urls91da7d12ab10c489d50b62371a3dcc42",
    platform: "competehub",
    name: "DeFi Mullet 黑客松 #1",
    shortName: "DeFi Mullet",
    city: "广州",
    country: "中国",
    dateRange: "2026年4月8日-14日",
    startDate: "2026-04-08",
    endDate: "2026-04-14",
    format: "offline",
    theme: "DeFi / Blockchain — 基于 LI.FI 创建收益产品",
    summary: "为期 7 天的线下 DeFi 黑客松，参赛者需基于 LI.FI 协议开发收益类产品。",
    prizePool: "¥36,000",
    tracks: ["DeFi", "Yield Products"],
    sponsors: ["LI.FI"],
    confidence: 70,
  },
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/luma59d80cac6565696d9aec9e26ba27d5ac",
    platform: "competehub",
    name: "广州 xB@B 黑客松",
    shortName: "xB@B 黑客松",
    city: "广州",
    country: "中国",
    dateRange: "2026年4月26日",
    startDate: "2026-04-26",
    endDate: "2026-04-26",
    format: "offline",
    theme: "综合科技创新",
    summary: "在广州举办的单日线下黑客松，奖金池达 18 万元。",
    prizePool: "¥180,000",
    confidence: 70,
  },
  {
    sourceUrl: "https://www.aicompetition-pz.com/about",
    platform: "web",
    name: "第 5 届琶洲算法大赛",
    shortName: "琶洲算法大赛",
    city: "广州",
    country: "中国",
    venue: "广州海珠区琶洲",
    dateRange: "2026年2月-9月",
    startDate: "2026-02-26",
    endDate: "2026-09-30",
    format: "hybrid",
    theme: "真场景、真数据、真转化 — AI 算法竞赛",
    summary: "广州琶洲试验区举办的第 5 届算法大赛，目标动员万支以上队伍参赛。",
    prizePool: "百万级数据券 + 百万级算力券",
    teams: "10000+",
    tracks: ["空地一体化协同 AI", "AI 大模型算法优选", "AI 创新应用", "全运会全民 AI", "国际 AI 赛"],
    organizers: ["广州市海珠区政府", "琶洲试验区"],
    confidence: 80,
  },

  // ============ 深圳 (6) ============
  {
    sourceUrl: "https://www.sixthtone.com/news/1018498",
    platform: "web",
    name: "She Code Lab 深圳女性硬件黑客松",
    shortName: "She Code Lab 深圳站",
    city: "深圳",
    country: "中国",
    venue: "深圳南头古城 / Z.Pilot Tech Space",
    dateRange: "2026年4月3日-6日",
    startDate: "2026-04-03",
    endDate: "2026-04-06",
    format: "offline",
    theme: "女性硬件创新 — 用代码续写故事",
    summary: "内地首场女性硬件黑客松，超过 300 人报名，百余名选手 48 小时开发创新硬件产品。90% 参赛者为女性，70% 为 00 后。",
    tracks: ["硬件创新", "AI + 健康", "AI + 安全"],
    organizers: ["She Nicest", "Coding Witch"],
    confidence: 85,
  },
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/urlsa0fca74878506b9c5a0a4382b283bd0b",
    platform: "competehub",
    name: "AttraX「春潮·Spring」深圳 OpenClaw 黑客松",
    shortName: "AttraX 春潮黑客松",
    city: "深圳",
    country: "中国",
    venue: "深圳啤酒小镇",
    dateRange: "2026年4月23日-26日",
    startDate: "2026-04-23",
    endDate: "2026-04-26",
    format: "offline",
    theme: "OpenClaw 开放创新",
    summary: "由清北学生发起的全球 Outlier 社区 AttraX 主办，基于 OpenClaw 创作软件、硬件或艺术作品。前 50 名免费住宿，获奖者可获国际黑客松门票。",
    tracks: ["软件开发", "硬件开发", "艺术创作", "OpenClaw"],
    organizers: ["AttraX"],
    confidence: 80,
  },
  {
    sourceUrl: "https://www.shejijingsai.com/2026/02/1505308.html",
    platform: "web",
    name: "2026 首届全球（深圳）AI+ 时尚创新应用大赛",
    shortName: "AI+ 时尚大赛",
    city: "深圳",
    country: "中国",
    venue: "深圳福田区",
    dateRange: "2025年12月-2026年7月",
    startDate: "2025-12-05",
    endDate: "2026-07-17",
    format: "hybrid",
    theme: "AI 新时尚·数智创未来",
    summary: "由深圳福田区政府指导、中国服装设计师协会主办的全球性 AI+ 时尚创新大赛，总决赛 7 月在深圳举行。",
    prizePool: "¥100,000（金鹭奖）",
    tracks: ["创意设计赛道", "创新解决赛道"],
    organizers: ["深圳市福田区文化广电旅游体育局", "中国服装设计师协会"],
    confidence: 80,
  },
  {
    sourceUrl: "https://zhenfund.com/Hackathon",
    platform: "web",
    name: "Level Up！真格 AI 游戏黑客松",
    shortName: "真格 AI 游戏黑客松",
    city: "深圳",
    country: "中国",
    dateRange: "2026年6月17日-18日",
    startDate: "2026-06-17",
    endDate: "2026-06-18",
    format: "offline",
    theme: "AI 游戏开发",
    summary: "真格基金主办的 36 小时线下黑客松，获胜团队有机会直接获得真格基金百万美元天使投资。",
    prizePool: "丰厚奖金 + 百万美元天使投资机会",
    tracks: ["游戏开发", "游戏生产力工具"],
    organizers: ["真格基金"],
    confidence: 85,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "Z-Heronix Deep 深圳女性黑客松",
    shortName: "Z-Heronix 深圳站",
    city: "深圳",
    country: "中国",
    venue: "T33 全时中心，南山区",
    dateRange: "2026年5月22日-24日",
    startDate: "2026-05-22",
    endDate: "2026-05-24",
    format: "offline",
    theme: "用代码续写故事 — AI 与硬件创新",
    summary: "她启 Z-Heronix 组织的女性黑客松深圳站，聚焦 AI 和硬件创新。",
    tracks: ["AI 创新", "硬件开发"],
    organizers: ["她启 Z-Heronix"],
    confidence: 70,
  },
  {
    sourceUrl: "https://harmonyosdev.csdn.net/69e9caed54b52172bc6c3d2f.html",
    platform: "web",
    name: "2026 HarmonyOS 创新赛·极客赛道",
    shortName: "HarmonyOS 极客赛道",
    city: "深圳",
    country: "中国",
    dateRange: "2026年3月-6月",
    startDate: "2026-03-18",
    endDate: "2026-06-30",
    format: "hybrid",
    theme: "HarmonyOS 系统级 AI 与空间计算",
    summary: "华为旗舰开发者竞赛，36 小时极限开发，TOP20 进入总冠军赛。决赛在 HDC 大会展示。",
    prizePool: "¥680,000+",
    tracks: ["安全与隐私保护", "全场景多设备协同", "AI 智慧体验", "3D 空间计算"],
    organizers: ["华为"],
    sponsors: ["华为"],
    confidence: 85,
  },

  // ============ 杭州 (6) ============
  {
    sourceUrl: "https://adventure-x.org/en",
    platform: "web",
    name: "AdventureX 2026",
    shortName: "AdventureX",
    city: "杭州",
    country: "中国",
    dateRange: "2026年7月（预计7月23-27日）",
    startDate: "2026-07-23",
    endDate: "2026-07-27",
    format: "offline",
    theme: "中国最大黑客松 — 燎原",
    summary: "由高中生创办的中国最大黑客松，800+ 参赛者，免费包吃住。面向 26 岁以下年轻人和在校学生。",
    prizePool: "$150,000+",
    organizers: ["AdventureX"],
    confidence: 85,
  },
  {
    sourceUrl: "https://www.competehub.dev/zh/competitions/urls6a26c3be14508ee86216412c6eef87fe",
    platform: "competehub",
    name: "2050 大会罕见病基因 AI 黑客松",
    shortName: "2050 罕见病 AI 黑客松",
    city: "杭州",
    country: "中国",
    venue: "云栖小镇（2050 大会会场）",
    dateRange: "2026年4月24日-26日",
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    format: "offline",
    theme: "用 AI 破解生命难题 — 罕见病基因诊断",
    summary: "在 2050 大会期间举办的 AI 医疗黑客松，48 小时解决 20 个真实罕见病案例。",
    tracks: ["变异检测", "表型-基因型关联", "诊断决策自动化", "开源工具平台开发"],
    organizers: ["2050 大会", "杭州市云栖科技创新基金会"],
    confidence: 80,
  },
  {
    sourceUrl: "https://lianpu.com/event/shu-qi-wan-mini-hei-ke-song",
    platform: "lianpu",
    name: "数栖湾 Mini 黑客松",
    shortName: "数栖湾 Mini Hack",
    city: "杭州",
    country: "中国",
    dateRange: "2026年4月18日",
    startDate: "2026-04-18",
    endDate: "2026-04-18",
    format: "offline",
    theme: "从想法到 Demo 落地",
    summary: "聚焦项目可行性与商业价值的迷你黑客松，帮助参赛者将想法快速转化为 Demo。",
    confidence: 60,
  },
  {
    sourceUrl: "https://www.hackquest.io/events/hackquest-x-monad-blitz-hangzhou",
    platform: "hackquest",
    name: "Monad Blitz 杭州站",
    shortName: "Monad Blitz 杭州",
    city: "杭州",
    country: "中国",
    dateRange: "2026年4月12日",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    format: "offline",
    theme: "Agentic Payment / 并行 EVM 区块链开发",
    summary: "Monad 基金会全球系列一日制线下黑客松杭州站，上午 Workshop 下午 Build Sprint。",
    prizePool: "$2,000",
    tracks: ["Agentic Payment", "Consumer Apps on Monad"],
    organizers: ["HackQuest", "Monad Foundation", "OpenBuild"],
    sponsors: ["Monad"],
    confidence: 75,
  },
  {
    sourceUrl: "https://lianpu.com/tag/hackathon",
    platform: "lianpu",
    name: "四小时黑客松 — 小白 AI 开发实操工坊",
    shortName: "4 小时 AI 黑客松",
    city: "杭州",
    country: "中国",
    dateRange: "2026年5月10日",
    startDate: "2026-05-10",
    endDate: "2026-05-10",
    format: "offline",
    theme: "零编程基础 AI 开发",
    summary: "面向零编程背景的初学者的 4 小时迷你黑客松/工坊，带领参与者从零上手 AI 开发。",
    confidence: 55,
  },
  {
    sourceUrl: "https://hhuh.io/china",
    platform: "web",
    name: "HackHarvard China Challenge 2026",
    shortName: "HackHarvard China",
    city: "杭州",
    country: "中国",
    dateRange: "2026年8月21日-23日",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    format: "offline",
    theme: "Designing Tomorrow's World",
    summary: "哈佛大学学生团队主办的中国区黑客松，36 小时线下开发，分初中、高中、大学生三组。",
    tracks: ["Education", "Safety", "Sustainability", "Smart Cities", "Mysterious Track"],
    organizers: ["HackHarvard", "合励教育"],
    confidence: 80,
  },

  // ============ 新加坡 (8) ============
  {
    sourceUrl: "https://www.superai.com/next-hackathon",
    platform: "web",
    name: "NEXT Hackathon 2026 (SuperAI)",
    shortName: "NEXT Hackathon",
    city: "新加坡",
    country: "新加坡",
    venue: "Marina Bay Sands",
    dateRange: "2026年6月9日-11日",
    startDate: "2026-06-09",
    endDate: "2026-06-11",
    format: "offline",
    theme: "AI 项目从零到一",
    summary: "SuperAI 大会旗下 36 小时线下黑客松，200 名精选开发者在 Marina Bay Sands 现场构建 AI 项目。完全免费参加，前 5 名面向 10,000 名与会者演示。",
    prizePool: "$130,000+",
    tracks: ["AI Agents", "AI Infrastructure", "AI Applications"],
    organizers: ["SuperAI"],
    sponsors: ["AWS", "Shellkode", "Vercel"],
    confidence: 90,
  },
  {
    sourceUrl: "https://technode.global/2026/05/14/sea-openai-launch-apac-ai-hackathon-series-starting-in-singapore-in-june/",
    platform: "web",
    name: "Sea x OpenAI Codex Hackathon",
    shortName: "Sea x OpenAI Codex",
    city: "新加坡",
    country: "新加坡",
    venue: "Shopee Building, 5 Science Park Drive",
    dateRange: "2026年6月6日",
    startDate: "2026-06-06",
    endDate: "2026-06-06",
    format: "offline",
    theme: "AI Coding Agents / 自主 AI 系统",
    summary: "Sea 与 OpenAI 联合举办的亚太首场 Codex 黑客松，限 40 支团队参加。使用 OpenAI Codex 等 AI 编程代理构建 AI 驱动产品。",
    prizePool: "$50,000 (OpenAI API 积分)",
    teams: "40",
    tracks: ["Autonomous and Adaptive AI", "AI-native Products", "Deep Domain AI"],
    organizers: ["Sea Limited", "OpenAI"],
    sponsors: ["Sea Limited", "OpenAI"],
    confidence: 90,
  },
  {
    sourceUrl: "https://www.dsta.gov.sg/brainhack",
    platform: "web",
    name: "BrainHack 2026",
    shortName: "BrainHack",
    city: "新加坡",
    country: "新加坡",
    dateRange: "决赛: 2026年6月10-11日",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    format: "hybrid",
    theme: "国防科技 / 网络安全 / AI / 太空 / 机器人",
    summary: "新加坡国防科技局(DSTA)主办的年度科技黑客松，包含网络安全 CTF、AI 训练部署、无人机编程、Web 开发等赛道。",
    tracks: ["Cyber Defenders (CDDC)", "TIL-AI", "Roboverse 无人机编程", "CODE_EXP Web 开发"],
    organizers: ["DSTA"],
    confidence: 85,
  },
  {
    sourceUrl: "https://naisc.aisingapore.org/",
    platform: "web",
    name: "National AI Student Challenge (NAISC) 2026",
    shortName: "NAISC 2026",
    city: "新加坡",
    country: "新加坡",
    venue: "AI Student Developer Conference",
    dateRange: "决赛: 2026年5月22-23日",
    startDate: "2026-05-22",
    endDate: "2026-05-23",
    format: "hybrid",
    theme: "AI 学生创新挑战",
    summary: "AI Singapore 主办的全国 AI 学生挑战赛，8 大赛道涵盖安防 AI、异常检测、学生 AI 助手、痴呆症检测等方向。",
    tracks: ["Certis 安防AI", "Huawei 异常检测", "Kaplan × Salesforce", "Micron 智能日志", "Singtel 数据漂移", "Workato MCP AI"],
    organizers: ["AI Singapore"],
    sponsors: ["Certis", "Huawei", "Kaplan", "Salesforce", "Micron", "Singtel", "Workato"],
    confidence: 85,
  },
  {
    sourceUrl: "https://build.tech.gov.sg/",
    platform: "web",
    name: "GovTech {build} Hackathon 2026",
    shortName: "GovTech {build}",
    city: "新加坡",
    country: "新加坡",
    venue: "GovTech 内部",
    dateRange: "2026年4月13日-5月25日",
    startDate: "2026-04-13",
    endDate: "2026-05-25",
    format: "offline",
    theme: "重塑数字政府体验",
    summary: "新加坡政府科技局内部黑客松，优秀团队可进入 {build} Incubator 孵化器。",
    organizers: ["GovTech Singapore"],
    confidence: 75,
  },
  {
    sourceUrl: "https://www.aihackathon.pro/",
    platform: "web",
    name: "AI Hackathon Series — Collaborate and Innovate",
    shortName: "AI Hackathon Series",
    city: "新加坡",
    country: "新加坡",
    venue: "SIA Theatrette, 79 Neil Road",
    dateRange: "2026年4月-5月",
    startDate: "2026-04-08",
    endDate: "2026-05-20",
    format: "hybrid",
    theme: "建筑环境 AI 解决方案",
    summary: "面向建筑环境专业人士的 AI 黑客松系列，开发设计优化、合规检查等方向的 AI 解决方案。",
    prizePool: "SGD $8,500",
    tracks: ["Design Optimization", "Compliance Checks", "Contract Management", "Sustainability"],
    organizers: ["Young Architects League", "SIA Digital Technology Committee"],
    sponsors: ["Autodesk", "Nemetschek Group"],
    confidence: 80,
  },
  {
    sourceUrl: "https://rapid-agent.devpost.com/",
    platform: "devpost",
    name: "Google Cloud Rapid Agent Hackathon",
    shortName: "Google Cloud Agent Hackathon",
    city: "新加坡",
    country: "新加坡",
    dateRange: "2026年5月1日-6月11日",
    startDate: "2026-05-01",
    endDate: "2026-06-11",
    format: "online",
    theme: "AI Agents 解决现实世界挑战",
    summary: "Google Cloud 全球在线黑客松，使用 Gemini 3 + Agent Builder + MCP 构建自主 AI Agent。",
    prizePool: "$50,000",
    tracks: ["AI Agents", "Autonomous Systems"],
    organizers: ["Google Cloud"],
    sponsors: ["Google Cloud", "GitLab"],
    confidence: 85,
  },
  {
    sourceUrl: "https://www.eventbrite.sg/d/singapore--singapore/hackathon/",
    platform: "eventbrite",
    name: "Eunos Hackathon",
    shortName: "Eunos Hackathon",
    city: "新加坡",
    country: "新加坡",
    venue: "Eunos Community Club",
    dateRange: "2026年6月21日",
    startDate: "2026-06-21",
    endDate: "2026-06-21",
    format: "offline",
    theme: "社区黑客松",
    summary: "在新加坡友诺士社区俱乐部举办的社区黑客松活动。",
    confidence: 50,
  },

  // ============ 线上/全国 (1) ============
  {
    sourceUrl: "https://medo.devpost.com/",
    platform: "devpost",
    name: "Build with MeDo Hackathon (百度)",
    shortName: "百度 MeDo 黑客松",
    city: "线上",
    country: "中国",
    dateRange: "2026年4月9日-5月20日",
    startDate: "2026-04-09",
    endDate: "2026-05-20",
    format: "online",
    theme: "No-Code AI 应用开发",
    summary: "百度全球黑客松，使用 MeDo 无代码平台构建全栈应用，提供 100 万免费 tokens。",
    prizePool: "$50,000+",
    tracks: ["Work & Productivity", "Business & E-commerce", "Lifestyle & Game", "Learning & Education"],
    organizers: ["百度"],
    sponsors: ["MeDo", "ERNIE"],
    confidence: 85,
  },
];

async function main() {
  console.log(`\n🚀 准备导入 ${hackathonData.length} 条黑客松数据到草稿箱...\n`);

  let success = 0;
  let failed = 0;

  for (const h of hackathonData) {
    try {
      await db.insert(draftHackathons).values({
        sourceUrl: h.sourceUrl,
        platform: h.platform,
        name: h.name,
        shortName: h.shortName || null,
        city: h.city,
        country: h.country,
        venue: h.venue || null,
        dateRange: h.dateRange,
        startDate: h.startDate ? new Date(h.startDate) : null,
        endDate: h.endDate ? new Date(h.endDate) : null,
        format: h.format,
        theme: h.theme || null,
        summary: h.summary,
        prizePool: h.prizePool || null,
        teams: h.teams || null,
        tracks: h.tracks || [],
        agenda: [],
        organizers: (h.organizers || []).map(name => ({ name })),
        sponsors: (h.sponsors || []).map(name => ({ name })),
        confidence: h.confidence,
        rawData: { importedAt: new Date().toISOString(), batch: "2026-05-20-multi-city-search" },
        status: 'pending',
      });
      console.log(`  ✅ ${h.city} | ${h.name}`);
      success++;
    } catch (err: any) {
      console.error(`  ❌ ${h.city} | ${h.name}: ${err.message}`);
      failed++;
    }
  }

  console.log(`\n📊 导入完成: ${success} 成功, ${failed} 失败（共 ${hackathonData.length} 条）\n`);
}

main().catch(console.error);
