#!/bin/zsh
# v3：锁定配色（参考图实测 token）+ v2 克制规则 + 参考图作为视觉锚点（-i 附图）
# 用法：./run-pages-v3.sh [01 02 ...]  不传参数则生成全部 7 页
cd "$(dirname "$0")"
mkdir -p neobrutalist-pages-v3
REF="$(pwd)/neobrutalist-pages-v3/01-home.png"   # 已定稿主页 = 唯一视觉锚点
[ -f "$REF" ] || REF="$(pwd)/theme-neobrutalist-blue.png"

DISCIPLINE='You are given a reference image: it is the APPROVED home screen of this WeChat mini-program and the LOCKED visual anchor. The page you generate must look like another screen of the SAME shipped app — match its exact style, color values, typography, component shapes, spacing rhythm and overall restraint. NEO-BRUTALIST but RESTRAINED and PREMIUM. EXACT COLOR TOKENS (do not drift): electric blue #0C51ED (primary buttons, selected states, blue blocks, tabbar active), lemon yellow #FBD902 (tiny accents only, <5% of screen), page background warm off-white #F4F1E8, cards pure white #FFFFFF, pure black #000000 for 2px borders and headline text. CRITICAL LAYOUT RULES: (1) generous whitespace, comfortable margins, do not fill edge-to-edge; (2) ONE focal hero element per screen that dominates, everything else quiet; (3) 2px black borders + hard offset black shadows (no blur) ONLY on primary cards and the main CTA — at most 4 shadowed elements per screen; (4) secondary info is clean and borderless, hierarchy via font weight/size/whitespace, not boxes; (5) illustration is ONLY allowed inside event poster thumbnails (like the wave poster in the reference) — NEVER as UI decoration. FORBIDDEN: mascot robots, comic explosion bubbles, halftone dot textures, pixel confetti, decorative stickers on UI chrome, ribbons except the small branded looping-ribbon H logo in the header, 3D extruded letters. PRODUCTION-GRADE BAR: this must look like a real shipped app screen a designer would hand to engineers — perfect alignment to an 8px grid, consistent 20px page margins, consistent corner radii, crisp legible Chinese text at realistic UI sizes, realistic data, no rendering artifacts or warped glyphs. BLUE BUDGET (strict, for visual comfort): blue covers AT MOST ~15% of the screen — reserved for ONE primary CTA, selected states, small icons/links and artwork inside event posters; NEVER use blue as section backgrounds or large panels; consecutive blue elements must be separated by calm white/off-white areas; all body text is black or dark grey, never blue paragraphs. VISUAL COMFORT: calm reading rhythm top-to-bottom, at most 2 saturated color areas visible in any viewport, generous quiet zones between sections so the eye can rest — friendly and breathable, never loud or fatiguing. Bold heavy Chinese type, PingFang-like. Premium finished WeChat mini-program mockup on a clean iPhone frame with status bar and WeChat capsule button top-right. Bottom tab bar 发现 / 赛程 / 消息 / 我的 (active tab in #0C51ED) unless it is a focused flow page. Real Chinese content, no lorem ipsum.'

gen () {
  local file="neobrutalist-pages-v3/$1"; local content="$2"
  echo ">>> $1"
  local BEFORE=$(mktemp); find ~/.codex/generated_images -name '*.png' > "$BEFORE"
  timeout 280 codex exec --sandbox danger-full-access -i "$REF" -- "Use your built-in image generation tool (gpt-image-1) to generate exactly 1 image (1024x1536). DO NOT write code. $DISCIPLINE PAGE: $content Report the path." 2>&1 | tail -2
  local NEW=$(comm -13 <(sort "$BEFORE") <(find ~/.codex/generated_images -name '*.png' | sort) | head -1)
  rm -f "$BEFORE"
  [ -n "$NEW" ] && cp "$NEW" "$file" && echo "<<< saved $file ($(stat -f %z "$file"))" || echo "!!! no image for $1"
}

want () { [ $# -eq 0 ] && return 0; for w in "$@"; do [[ "$PAGE" == "$w"* ]] && return 0; done; return 1; }

PAGE=01; want "$@" && gen "01-home.png" "Home = discovery page, reproduce the reference image layout faithfully with the exact tokens: top-left location 深圳 ▾, big black headline 发现黑客松, subtitle 找到最适合你的赛事, small line AI 帮你匹配，一键生成选手身份卡, small looping-ribbon H HackerTrip logo top-right of the headline block. Search bar with blue 搜索 button. Filter chips 全部(yellow selected) AI 硬件 出海 Web3 筛选. A 正在关注 strip: small wave poster thumbnail, 春潮 Spring, 深圳 线下 chips, 距离报名截止 12天, 匹配度 92% with slim blue progress bar. Section 精选推荐 with 3 illustrated sticker-poster cards in a carousel (春潮 Spring blue wave poster 04.23-04.25 深圳 线下; AdventureX 2026 green mountain poster 07.15-07.17 杭州 线下; 腾讯云 AI 黑客松 blue poster 06.01-06.02 上海 线上). Section 更多黑客松 with 2 list cards (BEYOND HACK DAY, dark pixel-text poster thumb, AI 企业出题 tags, 05.18-05.19 深圳; Global AI Hackathon 2026, dark globe poster thumb, AI 全球赛 线上+线下, 06.20-06.22 北京). Bottom blue CTA banner 生成我的身份卡 / AI 匹配最佳黑客松，一键生成 with yellow arrow. Tab bar with 发现 active."

PAGE=02; want "$@" && gen "02-schedule.png" "赛程 workspace tab. FOCAL HERO = one big status card: 活跃赛事 tag, AdventureX 2026, large countdown 距提交 5 天, 进度 62%, a 7-segment progress bar with stage labels 报名 组队 开发 中期 评审 优化 Demo (first 4 segments blue-filled, current stage highlighted), and one inset 下一任务 row. Below the hero: a QUIET task checklist of 3 items with simple square checkboxes (完善 Demo 核心流程 checked; 上传项目截图; 准备 3 分钟路演稿), borderless rows with whitespace. One small reminder note 今晚 20:00 团队同步. Tab bar with 赛程 active. Airy, not packed."

PAGE=03; want "$@" && gen "03-chat.png" "AI matching chat, focused flow (no tab bar). Clean airy conversation: right user bubble 我有一个 AI Agent 项目，想找线下黑客松, left AI reply asking to confirm 城市 / 阶段 / 偏好, small borderless quick-reply chips 深圳 上海 AI Agent 冲奖. FOCAL = one embedded event result card (small wave poster thumb, 春潮 Spring, match 94, one line 为什么推荐：适合 AI Agent 题型赛道，线下资源密集) — the only bordered/shadowed rich element. A 停止生成 pill. Clean bottom input bar with + 上下文 chip and blue send button. Generous spacing."

PAGE=04; want "$@" && gen "04-match.png" "匹配结果 page. FOCAL = project profile card at top: project name HackerTrip CLI, tech chips React LLM 产品设计 — bordered and prominent. Below, Top 5 list where ONLY #1 is emphasized (bigger, bordered, 全球 AI Agent 黑客松, match score 94 in green #13B36B, slim progress bar, tag AI Agent 赛道), and #2–#5 are QUIET borderless rows (rank, name, small blue score 88 85 82 79) separated by whitespace and hairlines. Tab bar absent (focused flow). Generous spacing, not five equal heavy boxes."

PAGE=05; want "$@" && gen "05-event.png" "黑客松详情 for AdventureX 2026, focused flow with back arrow. FOCAL HERO = large illustrated event poster (green mountain adventure style like the reference posters) with title AdventureX 2026 overlaid at top. Below, QUIET sections: a row of small borderless fact chips 07.22-07.26 / 43天 / 杭州 / 线下 / 奖池15万, a short 简介 paragraph (AdventureX 是一场面向全球开发者的创新盛会，聚焦前沿技术与真实场景结合), 赛道 tags AI Agent 创新应用 Web3, a slim AI 适配理由 note with a small spark icon, then a quiet row of two small text actions ⏰ 设提醒 and 问 AI 适合我吗. Fixed bottom bar with TWO buttons: primary blue CTA 去官方报名 (the only bold bordered button, opens official registration) and a quieter white secondary button 加入我的赛程. Breathing room everywhere."

PAGE=06; want "$@" && gen "06-identity.png" "身份卡工坊. Simple borderless tab switch 身份卡 / 配置卡 at top. FOCAL HERO = ONE large identity card centered with whitespace around it: blue circular avatar letter J, name Jayden, role AI Product Builder · 深圳, a small AI 判定角色 line 产品驱动的 AI 创造者, tech chips React LLM 产品设计 增长, small stats row 参赛 3 / 作品 2 / Skills 12. The card is white with 2px black border and hard shadow, with one small blue block accent. Bottom: 保存图片 (quiet secondary) and 分享找队友 (primary blue). Everything else minimal."

PAGE=07; want "$@" && gen "07-sync.png" "Skills 同步 page, focused flow. Top: small synced summary line GitHub @jayden · 已连接 12 个 Skills with a tiny check. FOCAL HERO = the 6-digit pairing code input as 6 bordered boxes centered with whitespace. Below: a clean numbered steps list 如何获得配对码 (1 装 Skill, 2 进入项目目录, 3 运行 /ht-scan-project, 4 复制 6 位码) as borderless rows. One primary blue 同步 button. Airy and focused."

PAGE=08; want "$@" && gen "08-inbox.png" "消息 inbox tab. Tab bar with 消息 active. Big black headline 消息. FOCAL = ONE urgent reminder card at top (the only bordered/shadowed element): small red clock accent, AdventureX 2026 报名截止仅剩 3 天, a small blue text link 去看看. Below it, QUIET grouped sections with whitespace: section label 截止提醒 with 2 borderless rows (each: small icon, one-line text like 春潮 Spring 报名将于 06.15 截止, time 2小时前, a tiny blue unread dot); section label 匹配结果 with 1 row (为你找到 5 个匹配赛事，最高 94 分, 昨天); section label 系统 with 1 row (身份卡已生成成功, 06.08). Hairline separators only, no boxes. Generous whitespace."

PAGE=09; want "$@" && gen "09-profile.png" "我的 profile tab. Tab bar with 我的 active. Big black headline 我的. FOCAL HERO = one large identity entry card (the only heavily bordered/shadowed element): blue circular avatar J, name Jayden, role AI Product Builder · 深圳, small chips React LLM, and a small blue arrow link 查看身份卡. Below the hero, QUIET grouped borderless rows separated by whitespace and hairlines, each row = small line icon + label + right chevron: group 参赛资产 (当前赛事 AdventureX 2026 · 报名中; 项目作品集 2; 收藏与报名清单 5); group 工具 (Agent · Skills 配置库 12; Skills 同步); at the very bottom a small quiet 设置 row. No boxes around rows, hierarchy by spacing. Generous whitespace."

echo "ALL DONE V3"
